### PR TITLE
fix #24

### LINKED ISSUE #24: Not found basic.c when installed from Hex
## Problem detail
When we write the `defpelemay` in our own projects, the generator try to read basic.c in deps/pelemay/lib/pelemay/generator/native. However, the path as `dir` attribute points just from the library, "lib/pelemay/generator/native/". It results file not found.

## Suggestion
When the file is not found, add the path for dependency, "deps/pelemay/".

### PR DESCRIPTION
**Pull request by zacky1972**
Finally, I've fixed #24!!!

Thank you, @muramasa8191 @olafura @josevalim and @ConnorRigby !!!

There are several points:

1. Discussed at #27  

`:code.lib_dir(:app)` and `Application.app_dir(:app, "priv/foo/bar")` are good tools to search the code and the application directory.

2. Discussed at #31 
There are three options: 

1. make the user add a pelemay compiler to THEIR mix.exs file. (this is the most common route)
2. make the user define an alias for the compile task. (this would accomplish the same thing as above, but be less "idiomatic")
3. in the generate step of defpelemay, just compile it manually there. (this would have the least user intervention, but might get kind of messy)

I adopt the approach 3.

### CODE REVIEW

**Comment by zacky1972** [comment]
It seems working well both in the directory of Pelemay itself and in another project directory imported Pelemay.

Would you review it ? @hisaway

**Comment by hisaway** [comment]
@zacky1972 I checked passing test on [pelemay_sample](https://github.com/zeam-vm/pelemay_sample) with following changes:
```
defp deps do
    [
      {:pelemay, git: "https://github.com/zeam-vm/pelemay.git", branch: "zacky1972_develop"},
    ]
end
```

**Comment by hisaway** [comment]
We should update pelemay version in Hex.
I'll merge this PR, after it.

**Comment by zacky1972** [comment]
This PR may not work well in Linux...
Would you test it in Linux? @hisaway

**Comment by zacky1972** [comment]
I've released it in Hex: https://hex.pm/packages/pelemay
I've also merged it into master. 
@hisaway

**Pull request merged**
