### PR TITLE
Support String.replace (Part 1)

### PR DESCRIPTION
**Pull request by hisaway**
Support String.replace in the following cases using #98 and #99 

- [x] case1
- [x] case2

```elixir
defpelemay do
  def case_1 replace_sample subject do
    String.replace(subject, @pattern, @replacement)
  end

  def case_2 replace_sample subject do
    subject |> String.replace(@pattern, @replacement)
  end
end
```

where `@pattern` and `@replacement` are constant.

branch name is `string_replace`.

### CODE REVIEW

**Comment by zacky1972** [comment]
Following error occurred:

```
warning: PelemayNifElixirStringTest.replace_STRING_Fizz_Buzz/1 is undefined or private. Did you mean one of:

      * replace_STRING_Fizz_Buzz/3

  lib/string_test.ex:14: StringTest.string_replace_1_2/0
```

source code is here:

```elixir
defmodule StringTest do
  require Pelemay
  import Pelemay

  @string """
  abcdefghi
  FizzBuzzFizzBuzz
  """

  def string_replace_1_1 do
    String.replace(@string, "Fizz", "Buzz")
  end

  defpelemay do
    def string_replace_1_2 do
      String.replace(@string, "Fizz", "Buzz")
    end
  end
end
```

**Comment by zacky1972** [comment]
It works well!

```
## LogisticMapBench
benchmark name           iterations   average time 
Pelemay String.replace     10000000   0.31 µs/op
original String.replace     1000000   1.29 µs/op
```

**Comment by zacky1972** [comment]
On iMac Pro

```
## StringTestBench
benchmark iterations   average time 
Pelemay     10000000   0.17 µs/op
original    10000000   0.67 µs/op
```

**Comment by zacky1972** [comment]
On Ryzen Threadripper:

```
## StringTestBench
benchmark iterations   average time 
Pelemay     10000000   0.21 µs/op
original    10000000   0.97 µs/op
```

**Comment by piacerex** [comment]
The bench is not found in this release...
Please add bench codes to Pelemay Github repo.

**Comment by zacky1972** [comment]
Benchmark code is here: https://github.com/zeam-vm/pelemay_sample

The reason why it is independent from Pelemay is to avoid importing Benchfella into Pelemay.

**Comment by piacerex** [comment]
Thx, please add pelemay_sample URL to the Pelemay README.

**Pull request closed without merging**
