### PR TITLE
towards fix #36

### LINKED ISSUE #36: Add basic functional testing of Pelemay
**Describe the bug**
There isn't any functional testing of Pelemay.

**To Reproduce**
omitted

**Expected behavior**
Basic functional testing brings future automatic CI. 

**Screenshots**
omitted

**Desktop (please complete the following information):**
It is required for all environments.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by zacky1972**
This PR should NOT be merged NOW because it isn't passed successfully.
I'll create a new issue corresponding to this.

This PR should be merged if the issue is solved.

### CODE REVIEW

**Comment by zacky1972** [comment]
@hisaway CI doesn't work well because `clang` is not installed nor set `PATH`.

**Comment by zacky1972** [comment]
@hisaway Or, PR #44 doesn't work in Linux...

**Comment by hisaway** [comment]
I installed clang-8 on docker image of CircleCI, because clang version on MacOS(10.14.6) is  based on it.

So there are two solution:

1. Make `clang` alias from clang-8 on docker image.
2. Change `@cc clang` to `@cc clang-8` in `lib/pelemay/generator/builder.ex:14`

**Comment by hisaway** [comment]
Commands `clang` and `clang-8` are same on MacOS.

**Comment by hisaway** [comment]
I created symbolic link clang from clang-8 and updated docker image.
We should enhance informations about Getting started on Linux.

**Pull request closed without merging**
